[package]
name = "rusty-moss"
version = "0.1.0"
authors = ["dwaris <dwaris@itclowd.de>"]
edition = "2021"

[dependencies]
dotenv = "0.15"
tracing = "0.1.23"
tracing-subscriber = "0.2"
num = "0.4.0"
serde = "1.0.132"
reqwest = { version = "0.11", features = ["json"] }

[dependencies.tokio]
version = "1.15.0"
features = ["full"]

[dependencies.serenity]
version = "0.10.9"
features = ["client", "framework", "model", "utils"]